# -*- coding: utf-8 -*-
"""SIC - IA 1 - Desvio Padrão

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HDTRsw0MtonfCmLoGS3oTKwCNs_ibzxV
"""

# Calcular a Amplitude

dados = [8,9,7,10,9,8,10,10,11,8,8,9,10,12,8,10,7,8]

# Encontra o máximo e o mínimo dos números
maior = max(dados)
menor = min(dados)
# Calcula a amplitude como a diferença entre o máximo e o mínimo
amplitude = maior - menor

print("A amplitude é:",amplitude)

# Calcular a média de valores de uma lista
dados = [8,9,7,10,9,8,10,10,11,8,8,9,10,12,8,10,7,8]
soma = sum(dados)
media = soma / len(dados)
print("A média dos números é:", media)

# Calcular Variância e desvio padrão
import math
#Calcular a média de valores de uma lista
dados = [8,9,7,10,9,8,10,10,11,8,8,9,10,12,8,10,7,8]
soma = sum(dados)
media = soma / len(dados)
print("A média dos números é", media)# cálculo da média

# Calcula a soma dos quadrados das diferenças em relação à média
soma_quadrados_diff = sum((x - media)**2 for x in dados)

# Calcula a variância
variancia = soma_quadrados_diff / (len(dados)-1)

# Calcula o desvio padrão como a raiz quadrada da variância
desvio_pad = math.sqrt(variancia)
print("A variância é", variancia)
print("O desvio padrão é", desvio_pad)