# -*- coding: utf-8 -*-
"""CAPÍTULO 2 - QUIZZ - SIC

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jGn8AIAJga45kXgjBi32SbNDuiFLV8n5
"""

# Exercício 1

s1 = ["Eu amo", "Eu gosto de"]
s2 = ["Panqueca", "Suco de laranja", "Café"]
for i in s1:
    for j in s2:
      print(i, j)

# Exercício 2

person = {'Name': 'Davi', 'Age': 26, 'Weight': 82, 'Job': 'Cientista de dados'}
print(person)
person['Pai'] = "Antônio"
print(person)

# Exercício 3

list = [5, 6, 3, 9, 2, 12, 3, 8, 7]
for i in range(len(list) - 1):
  if list[i] > list[i+1]:
    list[i], list[i + 1] = list[i + 1], list[i]
print(list)

# Exercício 4

list0 =  [[1, 2], [3, 4], [5, 6]]
list1 = []
for i in list0:
  for j in i:
    list1.append(j)
print(list1, end = ' ')

# Exercício 5

maria = {'coreano': 94, 'ingles': 91, 'matematica': 89, 'ciencia': 83}
nota = maria.values()
soma = sum(nota)
num_curso = len(nota)
media = soma / num_curso
print("A média de Maria é:", media)

# Exercício 6

import copy
school = { 'kim': {'age': 16, 'hei': 170, 'grade': 3}, 'lee': {'age': 15, 'hei': 168, 'grade': 2}, 'choi': {'age': 14, 'hei': 173, 'grade': 1}}
school2 = copy.deepcopy(school)
print(school is school2)

# Exercício 7

notas = (('Davi',  88,  95, 90), ('Felipe', 83, 98, 81), ('Luciano', 81, 97, 98), ('Rodrigo', 82, 89, 83))
nomes, ing, mat, cien = zip(*notas)
media = sum(mat) / len(mat)
print("A média das notas de matemática é: ", media)