# -*- coding: utf-8 -*-
"""CAPÍTULO 7 - QUIZZ - SIC

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QCr7prPZlfxb2-dXAUYg-EAeXMiI_TxP
"""

# Exercício 1

# Converter os seguintes dados do dicionário em um objeto de dataframe usando Pandas. (O objeto dataframe é nomeado como df)

import pandas as pd
d = {'col1': [1, 2], 'col2': [3, 4], 'col3': [5, 6], 'col4': [7, 8]}
df = pd.DataFrame(d)
print(df)

# Exercício 2

# No quadro de dados criado na pergunta 1, criar um novo quadro de dados que consiste apenas de dados de coluna com o nome da coluna "col4".
# (O quadro de dados é nomeado como new_df.)

import pandas as pd
d = {'col1': [1, 2], 'col2': [3, 4], 'col3': [5, 6], 'col4': [7, 8]}
df = pd.DataFrame(d)

new_df = df[['col4']]
print(new_df)

# Exercício 3

# O índice do quadro de dados criado na Pergunta 1 é 0,1. Escreva um comando para mudar o nome destes índices para primeiro e segundo.

import pandas as pd
d = {'col1': [1, 2], 'col2': [3, 4], 'col3': [5, 6], 'col4': [7, 8]}
df = pd.DataFrame(d)

df.rename(index={0: 'primeiro', 1: 'segundo'}, inplace = True)
print(df)

# Exercício 4

# Escreva um comando para procurar por dados faltantes no quadro de dados df criado na Pergunta 1 e imprima o resultado.
# (Entretanto, os dados em falta devem ser devolvidos como Verdadeiros).

import pandas as pd
d = {'col1': [1, 2], 'col2': [3, 4], 'col3': [5, 6], 'col4': [7, 8]}
df = pd.DataFrame(d)

print(df.isnull(), '\n')
print(df.isnull().sum())

# Exercício 5

# Escreva um comando para verificar o resumo estatístico descritivo (desvio padrão, valor mínimo, modo, etc.)
# do quadro de dados df criado na Pergunta 1 e imprima o resultado.

import pandas as pd
d = {'col1': [1, 2], 'col2': [3, 4], 'col3': [5, 6], 'col4': [7, 8]}
df = pd.DataFrame(d)

print(df.describe(), '\n\n')
print(df.mean(), '\n\n') # media
print(df.median(), '\n\n') # mediana
print(df.mode(), '\n\n') # moda
print(df.var(), '\n\n') # variancia
print(df.std(), '\n\n') # desvio padrão