# -*- coding: utf-8 -*-
"""Turtle - Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LsNDQYrq0KLmQBzwB72AX66ysytyQ-2R

# **Colab Turtle**
- VSCode: install turtle
"""

#Instalando a Biblioteca
!pip3 install ColabTurtle

import ColabTurtle.Turtle as t
t.initializeTurtle()

t.clear()
side_length = 100
angle = 360/8

for i in range(8):
  t.forward(side_length)
  t.right(angle)

t.clear()
for i in range(100):
  t.forward(i)
  t.left(93)
t.done()

t.clear()

"""Outra coisa..."""

# Fazendo um desenho com o turtle
# Se você executar o código abaixo, uma janela separada aparece e um cursor desenha uma imagem.

import turtle as t # t é um apelido do módulo turtle.

t.setup(width = 400, height = 400) # função t.setup atribui o tamanho, título e outras características da janela de bate-papo.
for i in range(200):
  t.forward(i)
  t.left(93)
t.done()